name: Lint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Get pnpm store directory
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check code lint
        run: pnpm run lint
